version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chg_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}